# Generated by Django 3.0.5 on 2020-04-14 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200414_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 17, 42, 31, 492619)),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 17, 42, 31, 491582)),
        ),
    ]
