# Generated by Django 3.0.5 on 2020-04-17 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200417_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 20, 17, 22, 174513)),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 20, 17, 22, 176510)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 20, 17, 22, 173516)),
        ),
    ]
