# Generated by Django 3.0.5 on 2020-04-19 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 19, 15, 51, 54, 49991)),
        ),
        migrations.AlterField(
            model_name='assignmentsubmit',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 19, 15, 51, 54, 50988)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 19, 15, 51, 54, 48994)),
        ),
    ]
