# Generated by Django 3.0.5 on 2020-04-14 09:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment/')),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 14, 30, 29, 806846))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AssignmentCreatedBy', to='users.Profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentGroup', to='users.Group')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('jwt', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('members', models.TextField(blank=True, null=True)),
                ('frame_details', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('notice', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 14, 30, 29, 805845))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotesOwnerCreatedBy', to='users.Profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotesOwner', to='users.Group')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment/')),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 14, 30, 29, 806846))),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.Assignment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Profile')),
            ],
        ),
    ]
