# Generated by Django 3.0.5 on 2020-04-14 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_auto_20200414_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 17, 42, 31, 495571)),
        ),
        migrations.AlterField(
            model_name='assignmentsubmit',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 17, 42, 31, 495571)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 17, 42, 31, 494576)),
        ),
    ]
