# Generated by Django 3.0.5 on 2020-04-14 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_auto_20200414_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 17, 56, 54, 394218)),
        ),
        migrations.AlterField(
            model_name='assignmentsubmit',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 17, 56, 54, 395212)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 17, 56, 54, 394218)),
        ),
    ]
