# Generated by Django 3.0.5 on 2020-04-14 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_auto_20200414_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notice',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 18, 1, 59, 166940)),
        ),
        migrations.AlterField(
            model_name='assignmentsubmit',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 18, 1, 59, 168933)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 18, 1, 59, 165942)),
        ),
    ]
